backend:
  name: github
  repo: marcosjrocha-art/educacaofinanceirasp
  branch: main
  auth_type: pkce # Adicione esta linha

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Artigos"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Resumo", name: "description", widget: "text" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
